import { Property, NeighborhoodData, MarketTrend } from './types';

export const properties: Property[] = [
  {
    id: 1,
    title: "Sea-Facing Sanctuary",
    location: "Bandra West, Hill Road",
    area: "Bandra West",
    price: 45000000,
    priceLabel: "₹4.5 Cr",
    pricePerSqft: 27272,
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1650,
    builtUpArea: 1850,
    floor: "12th Floor",
    totalFloors: 15,
    facing: "West",
    parking: 2,
    furnishing: "Semi-Furnished",
    possession: "Ready to Move",
    ageOfProperty: "2 Years",
    amenities: ["Sea View", "Gym", "Swimming Pool", "24/7 Security", "Lift", "Power Backup"],
    featured: true,
    verified: true,
    imageUrl: "luxury-sea-facing-apartment.jpg",
    coordinates: {lat: 19.0596, lng: 72.8295}
  },
  {
    id: 2,
    title: "Modern Beach Living",
    location: "Juhu Tara Road, Near Beach",
    area: "Juhu",
    price: 32500000,
    priceLabel: "₹3.25 Cr",
    pricePerSqft: 29090,
    type: "Sale",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1100,
    builtUpArea: 1250,
    floor: "8th Floor",
    totalFloors: 12,
    facing: "North",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Under Construction",
    possessionDate: "Dec 2025",
    ageOfProperty: "New Launch",
    amenities: ["Gym", "Swimming Pool", "Security", "Lift", "Garden"],
    featured: true,
    verified: true,
    imageUrl: "modern-2bhk-juhu.jpg",
    coordinates: {lat: 19.0988, lng: 72.8265}
  },
  {
    id: 3,
    title: "Business Hub Office Space",
    location: "Andheri East, Near Metro",
    area: "Andheri East",
    price: 9500000,
    priceLabel: "₹95 L",
    pricePerSqft: 11176,
    type: "Sale",
    category: "Commercial",
    carpetArea: 850,
    builtUpArea: 950,
    floor: "4th Floor",
    totalFloors: 8,
    parking: 3,
    furnishing: "Furnished",
    possession: "Ready to Move",
    ageOfProperty: "5 Years",
    amenities: ["High-Speed Lifts", "24/7 Security", "Power Backup", "Cafeteria", "Parking"],
    featured: false,
    verified: true,
    imageUrl: "office-space-andheri.jpg",
    coordinates: {lat: 19.1136, lng: 72.8697}
  },
  {
    id: 4,
    title: "Penthouse Paradise",
    location: "Hiranandani Gardens, Powai",
    area: "Powai",
    price: 75000000,
    priceLabel: "₹7.5 Cr",
    pricePerSqft: 23437,
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 5,
    carpetArea: 3200,
    builtUpArea: 3600,
    floor: "Penthouse",
    totalFloors: 15,
    facing: "East",
    parking: 3,
    furnishing: "Fully Furnished",
    possession: "Ready to Move",
    ageOfProperty: "3 Years",
    amenities: ["Private Pool", "Terrace Garden", "Gym", "Clubhouse", "Smart Home", "Security"],
    featured: true,
    verified: true,
    imageUrl: "penthouse-powai.jpg",
    coordinates: {lat: 19.1197, lng: 72.9068}
  },
  {
    id: 5,
    title: "Starter Home Deal",
    location: "Santacruz West, Near Station",
    area: "Santacruz West",
    price: 12500000,
    priceLabel: "₹1.25 Cr",
    pricePerSqft: 22727,
    type: "Sale",
    category: "Residential",
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 550,
    builtUpArea: 625,
    floor: "3rd Floor",
    totalFloors: 5,
    facing: "East",
    parking: 1,
    furnishing: "Semi-Furnished",
    possession: "Ready to Move",
    ageOfProperty: "8 Years",
    amenities: ["Security", "Lift", "Water Supply"],
    featured: false,
    verified: true,
    imageUrl: "1bhk-santacruz.jpg",
    coordinates: {lat: 19.0840, lng: 72.8389}
  },
  {
    id: 6,
    title: "Luxury Worli Rental",
    location: "Worli Sea Face",
    area: "Worli",
    price: 250000,
    priceLabel: "₹2.5 L/mo",
    pricePerSqft: 13888,
    type: "Rent",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1800,
    builtUpArea: 2000,
    floor: "18th Floor",
    totalFloors: 25,
    facing: "West",
    parking: 2,
    furnishing: "Fully Furnished",
    possession: "Available Now",
    deposit: "₹7.5 Lakhs",
    ageOfProperty: "3 Years",
    amenities: ["Sea View", "Gym", "Swimming Pool", "Concierge", "Security", "Clubhouse"],
    featured: true,
    verified: true,
    imageUrl: "luxury-rental-worli.jpg",
    coordinates: {lat: 19.0176, lng: 72.8161}
  },
  {
    id: 7,
    title: "Compact Studio Apartment",
    location: "Andheri West, Lokhandwala",
    area: "Andheri West",
    price: 8500000,
    priceLabel: "₹85 L",
    pricePerSqft: 21250,
    type: "Sale",
    category: "Residential",
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 400,
    builtUpArea: 450,
    floor: "6th Floor",
    totalFloors: 10,
    facing: "South",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Ready to Move",
    ageOfProperty: "3 Years",
    amenities: ["Security", "Lift", "Power Backup", "Gym"],
    featured: false,
    verified: true,
    imageUrl: "studio-andheri.jpg",
    coordinates: {lat: 19.1368, lng: 72.8340}
  },
  {
    id: 8,
    title: "Spacious Family Home",
    location: "Bandra East, Near BKC",
    area: "Bandra East",
    price: 55000000,
    priceLabel: "₹5.5 Cr",
    pricePerSqft: 30555,
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1800,
    builtUpArea: 2000,
    floor: "10th Floor",
    totalFloors: 14,
    facing: "North",
    parking: 2,
    furnishing: "Semi-Furnished",
    possession: "Ready to Move",
    ageOfProperty: "1 Year",
    amenities: ["Gym", "Swimming Pool", "Clubhouse", "Security", "Kids Play Area"],
    featured: false,
    verified: true,
    imageUrl: "3bhk-bandra-east.jpg",
    coordinates: {lat: 19.0596, lng: 72.8656}
  },
  {
    id: 9,
    title: "Budget-Friendly 2BHK",
    location: "Malad West",
    area: "Malad West",
    price: 14500000,
    priceLabel: "₹1.45 Cr",
    pricePerSqft: 18125,
    type: "Sale",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 800,
    builtUpArea: 900,
    floor: "5th Floor",
    totalFloors: 12,
    facing: "East",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Under Construction",
    possessionDate: "Mar 2026",
    ageOfProperty: "New Launch",
    amenities: ["Lift", "Security", "Power Backup", "Gym"],
    featured: false,
    verified: true,
    imageUrl: "2bhk-malad.jpg",
    coordinates: {lat: 19.1865, lng: 72.8353}
  },
  {
    id: 10,
    title: "Premium Office in Powai",
    location: "Powai, Hiranandani Business Park",
    area: "Powai",
    price: 15000000,
    priceLabel: "₹1.5 Cr",
    pricePerSqft: 12500,
    type: "Sale",
    category: "Commercial",
    carpetArea: 1200,
    builtUpArea: 1350,
    floor: "7th Floor",
    totalFloors: 10,
    parking: 4,
    furnishing: "Furnished",
    possession: "Ready to Move",
    ageOfProperty: "2 Years",
    amenities: ["High-Speed Lifts", "24/7 Security", "Power Backup", "Cafeteria", "Conference Rooms"],
    featured: false,
    verified: true,
    imageUrl: "office-powai.jpg",
    coordinates: {lat: 19.1197, lng: 72.9068}
  },
  {
    id: 11,
    title: "Luxury Villa in Juhu",
    location: "Juhu Scheme",
    area: "Juhu",
    price: 125000000,
    priceLabel: "₹12.5 Cr",
    pricePerSqft: 31250,
    type: "Sale",
    category: "Residential",
    bedrooms: 5,
    bathrooms: 6,
    carpetArea: 4000,
    builtUpArea: 4500,
    floor: "Independent",
    facing: "West",
    parking: 5,
    furnishing: "Fully Furnished",
    possession: "Ready to Move",
    ageOfProperty: "5 Years",
    amenities: ["Private Pool", "Garden", "Home Theater", "Gym", "Security", "Staff Quarters"],
    featured: true,
    verified: true,
    imageUrl: "villa-juhu.jpg",
    coordinates: {lat: 19.0988, lng: 72.8265}
  },
  {
    id: 12,
    title: "Cozy 1BHK Rental",
    location: "Khar West",
    area: "Khar",
    price: 45000,
    priceLabel: "₹45k/mo",
    pricePerSqft: 90,
    type: "Rent",
    category: "Residential",
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 500,
    builtUpArea: 550,
    floor: "2nd Floor",
    totalFloors: 4,
    facing: "North",
    parking: 0,
    furnishing: "Semi-Furnished",
    possession: "Available Now",
    deposit: "₹1.35 Lakhs",
    ageOfProperty: "5 Years",
    amenities: ["Security", "Water Supply"],
    featured: false,
    verified: true,
    imageUrl: "1bhk-rental-khar.jpg",
    coordinates: {lat: 19.0728, lng: 72.8345}
  },
  {
    id: 13,
    title: "Modern 3BHK in Lower Parel",
    location: "Lower Parel, Near Phoenix Mills",
    area: "Lower Parel",
    price: 68000000,
    priceLabel: "₹6.8 Cr",
    pricePerSqft: 34000,
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 2000,
    builtUpArea: 2200,
    floor: "20th Floor",
    totalFloors: 30,
    facing: "South",
    parking: 2,
    furnishing: "Semi-Furnished",
    possession: "Ready to Move",
    ageOfProperty: "2 Years",
    amenities: ["Gym", "Swimming Pool", "Clubhouse", "Security", "Sky Deck", "Concierge"],
    featured: true,
    verified: true,
    imageUrl: "3bhk-lower-parel.jpg",
    coordinates: {lat: 18.9975, lng: 72.8306}
  },
  {
    id: 14,
    title: "Retail Space in Linking Road",
    location: "Bandra West, Linking Road",
    area: "Bandra West",
    price: 35000000,
    priceLabel: "₹3.5 Cr",
    pricePerSqft: 70000,
    type: "Sale",
    category: "Commercial",
    carpetArea: 500,
    builtUpArea: 550,
    floor: "Ground Floor",
    totalFloors: 1,
    parking: 2,
    furnishing: "Unfurnished",
    possession: "Ready to Move",
    ageOfProperty: "10 Years",
    amenities: ["High Footfall", "Prime Location", "Wide Frontage"],
    featured: false,
    verified: true,
    imageUrl: "retail-linking-road.jpg",
    coordinates: {lat: 19.0596, lng: 72.8295}
  },
  {
    id: 15,
    title: "Spacious 4BHK with Study",
    location: "Worli, Lodha World Towers",
    area: "Worli",
    price: 95000000,
    priceLabel: "₹9.5 Cr",
    pricePerSqft: 29687,
    type: "Sale",
    category: "Residential",
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 3200,
    builtUpArea: 3500,
    floor: "45th Floor",
    totalFloors: 50,
    facing: "West",
    parking: 3,
    furnishing: "Fully Furnished",
    possession: "Ready to Move",
    ageOfProperty: "1 Year",
    amenities: ["Sea View", "Private Lift", "Gym", "Pool", "Clubhouse", "Concierge", "Valet"],
    featured: true,
    verified: true,
    imageUrl: "4bhk-worli-towers.jpg",
    coordinates: {lat: 19.0176, lng: 72.8161}
  },
  {
    id: 16,
    title: "Budget 2BHK Investment",
    location: "Goregaon East",
    area: "Goregaon East",
    price: 11500000,
    priceLabel: "₹1.15 Cr",
    pricePerSqft: 14375,
    type: "Sale",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 800,
    builtUpArea: 900,
    floor: "8th Floor",
    totalFloors: 15,
    facing: "North",
    parking: 1,
    furnishing: "Unfurnished",
    possession: "Under Construction",
    possessionDate: "Jun 2026",
    ageOfProperty: "New Launch",
    amenities: ["Gym", "Lift", "Security", "Power Backup"],
    featured: false,
    verified: true,
    imageUrl: "2bhk-goregaon.jpg",
    coordinates: {lat: 19.1652, lng: 72.8526}
  },
  {
    id: 17,
    title: "Co-Working Office Space",
    location: "Andheri West, Veera Desai",
    area: "Andheri West",
    price: 120000,
    priceLabel: "₹1.2 L/mo",
    pricePerSqft: 150,
    type: "Rent",
    category: "Commercial",
    carpetArea: 800,
    builtUpArea: 900,
    floor: "3rd Floor",
    totalFloors: 5,
    parking: 2,
    furnishing: "Fully Furnished",
    possession: "Available Now",
    deposit: "₹3.6 Lakhs",
    ageOfProperty: "2 Years",
    amenities: ["High-Speed Internet", "Meeting Rooms", "Cafeteria", "24/7 Access", "Parking"],
    featured: false,
    verified: true,
    imageUrl: "coworking-andheri.jpg",
    coordinates: {lat: 19.1368, lng: 72.8340}
  },
  {
    id: 18,
    title: "Beachfront 3BHK",
    location: "Versova, Near Beach",
    area: "Versova",
    price: 42000000,
    priceLabel: "₹4.2 Cr",
    pricePerSqft: 28000,
    type: "Sale",
    category: "Residential",
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1500,
    builtUpArea: 1650,
    floor: "9th Floor",
    totalFloors: 12,
    facing: "West",
    parking: 2,
    furnishing: "Semi-Furnished",
    possession: "Ready to Move",
    ageOfProperty: "4 Years",
    amenities: ["Beach View", "Gym", "Swimming Pool", "Security", "Garden"],
    featured: false,
    verified: true,
    imageUrl: "3bhk-versova.jpg",
    coordinates: {lat: 19.1336, lng: 72.8125}
  },
  {
    id: 19,
    title: "Luxury 2BHK Rental",
    location: "Prabhadevi, Near Siddhivinayak",
    area: "Prabhadevi",
    price: 185000,
    priceLabel: "₹1.85 L/mo",
    pricePerSqft: 185,
    type: "Rent",
    category: "Residential",
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1000,
    builtUpArea: 1100,
    floor: "15th Floor",
    totalFloors: 20,
    facing: "East",
    parking: 1,
    furnishing: "Fully Furnished",
    possession: "Available Now",
    deposit: "₹5.55 Lakhs",
    ageOfProperty: "1 Year",
    amenities: ["Gym", "Swimming Pool", "Security", "Clubhouse", "Power Backup"],
    featured: false,
    verified: true,
    imageUrl: "2bhk-rental-prabhadevi.jpg",
    coordinates: {lat: 19.0144, lng: 72.8310}
  },
  {
    id: 20,
    title: "Premium Showroom Space",
    location: "Santacruz West, SV Road",
    area: "Santacruz West",
    price: 28000000,
    priceLabel: "₹2.8 Cr",
    pricePerSqft: 56000,
    type: "Sale",
    category: "Commercial",
    carpetArea: 500,
    builtUpArea: 550,
    floor: "Ground Floor",
    totalFloors: 1,
    parking: 3,
    furnishing: "Unfurnished",
    possession: "Ready to Move",
    ageOfProperty: "5 Years",
    amenities: ["Prime Location", "Wide Frontage", "High Visibility", "Parking"],
    featured: false,
    verified: true,
    imageUrl: "showroom-santacruz.jpg",
    coordinates: {lat: 19.0840, lng: 72.8389}
  }
];

export const neighborhoodData: Record<string, NeighborhoodData> = {
  "Bandra West": {
    overallScore: 9.2,
    schools: { score: 9, nearby: ["Bombay Scottish - 800m", "Jamnabai - 1.2km"] },
    transport: { score: 8, details: ["Bandra Station - 800m", "Metro 2026"] },
    healthcare: { score: 10, nearby: ["Lilavati - 500m", "Hinduja - 1.5km"] },
    shopping: { score: 9, details: ["Linking Road", "Hill Road", "50+ restaurants"] },
    recreation: { score: 8, details: ["Joggers Park", "Bandstand"] },
    appreciation: { score: 9, rate: "12% annual" }
  },
  "Juhu": {
    overallScore: 8.5,
    schools: { score: 8, nearby: ["JVPD Schools", "Mithibai College"] },
    transport: { score: 7, details: ["Vile Parle Station", "Juhu Tara Road"] },
    healthcare: { score: 9, nearby: ["Nanavati Hospital", "Cooper Hospital"] },
    shopping: { score: 10, details: ["Juhu Beach Markets", "Premium Boutiques"] },
    recreation: { score: 9, details: ["Juhu Beach", "Prithvi Theatre"] },
    appreciation: { score: 8, rate: "8% annual" }
  },
  "Powai": {
    overallScore: 9.0,
    schools: { score: 9, nearby: ["Hiranandani Foundation", "IIT Bombay"] },
    transport: { score: 7, details: ["JVLR", "Upcoming Metro Line 6"] },
    healthcare: { score: 8, nearby: ["Dr. L H Hiranandani Hospital"] },
    shopping: { score: 9, details: ["Galleria", "Hiranandani High Street"] },
    recreation: { score: 9, details: ["Powai Lake", "Nirvana Park"] },
    appreciation: { score: 10, rate: "15% annual" }
  }
};

export const marketTrends: MarketTrend[] = [
  { month: "Jan", bandraWest: 38000, juhu: 35000, powai: 20000, andheri: 18000 },
  { month: "Feb", bandraWest: 39500, juhu: 35500, powai: 20500, andheri: 18500 },
  { month: "Mar", bandraWest: 40000, juhu: 36000, powai: 21000, andheri: 19000 },
  { month: "Apr", bandraWest: 41000, juhu: 36200, powai: 21200, andheri: 19200 },
  { month: "May", bandraWest: 42500, juhu: 36800, powai: 21800, andheri: 19800 },
  { month: "Jun", bandraWest: 43000, juhu: 37000, powai: 22000, andheri: 20000 },
  { month: "Jul", bandraWest: 43500, juhu: 37200, powai: 22200, andheri: 20200 },
  { month: "Aug", bandraWest: 44000, juhu: 37500, powai: 22500, andheri: 20500 },
  { month: "Sep", bandraWest: 44500, juhu: 37800, powai: 22800, andheri: 20800 },
  { month: "Oct", bandraWest: 45000, juhu: 38000, powai: 23000, andheri: 21000 },
  { month: "Nov", bandraWest: 45500, juhu: 38200, powai: 23500, andheri: 21500 },
  { month: "Dec", bandraWest: 45000, juhu: 38000, powai: 23000, andheri: 21000 },
];
